name: Deploy Website using rsync (with password only)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install rsync and sshpass
      run: |
        sudo apt-get install -y rsync sshpass

    - name: Deploy files using rsync over SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SFTP_PRIVATE_KEY" > ~/.ssh/id_rsa  # Store SSH key if you're using SSH keys for other connections
        chmod 600 ~/.ssh/id_rsa  # Ensure correct permissions for the SSH key

        # Disable host key verification to avoid the "Host key verification failed" error
        echo "Host ${SFTP_HOST}" >> ~/.ssh/known_hosts
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

        # Run rsync using password authentication (disable SSH key authentication)
        rsync -avz -e "ssh -o PubkeyAuthentication=no -p 22" ./ ${SFTP_USERNAME}@${SFTP_HOST}:${REMOTE_PATH}
      env:
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}  # cPanel username
        SFTP_HOST: ${{ secrets.SFTP_HOST }}  # cPanel SFTP host
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}  # Remote directory to deploy to
