name: Deploy Website as Zip Archive

on:
  push:
    branches:
      - main  # Trigger deployment on the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install zip and sshpass
      run: sudo apt-get install -y zip sshpass

    - name: Create zip archive
      run: zip -r my-website.zip ./  # Zip up the entire website

    - name: Deploy zip file via SCP
      run: |
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" scp -P 22 my-website.zip ${SFTP_USERNAME}@${SFTP_HOST}:${REMOTE_PATH}/

    - name: Unzip on server
      run: |
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 22 ${SFTP_USERNAME}@${SFTP_HOST} "unzip -o ${REMOTE_PATH}/my-website.zip -d ${REMOTE_PATH}/"
      env:
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
