name: Deploy Static Website using rsync

on:
  push:
    branches:
      - main  # Trigger the deployment when pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub's Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Install rsync and sshpass
      run: |
        sudo apt-get install -y rsync sshpass  # Install rsync for fast file transfers

    - name: Deploy files using rsync over SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SFTP_PRIVATE_KEY" > ~/.ssh/id_rsa  # Store the SSH key (if using keys)
        chmod 600 ~/.ssh/id_rsa  # Ensure correct permissions for SSH key

        # Disable host key verification
        echo "Host ${SFTP_HOST}" >> ~/.ssh/known_hosts
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

        # Run rsync to deploy files efficiently
        rsync -avz -e "ssh -p 22" ./ ${SFTP_USERNAME}@${SFTP_HOST}:${REMOTE_PATH}
      env:
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}  # cPanel username
        SFTP_HOST: ${{ secrets.SFTP_HOST }}  # cPanel SFTP host
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}  # Remote directory to deploy to
