name: Deploy Static Website via SFTP

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This checks out the code from the repository

    - name: Install SFTP client
      run: sudo apt-get install -y openssh-client

    - name: Upload via SFTP
      run: |
        mkdir -p ~/.ssh
        echo "$SFTP_PRIVATE_KEY" > ~/.ssh/id_rsa  # Use GitHub Secrets to store your private key
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" > ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config  # Disable host key checking for simplicity
        sftp -oPort=${{ secrets.SFTP_PORT }} ${SFTP_USERNAME}@${{ secrets.SFTP_HOST }} << EOF
        put -r ./ ${REMOTE_PATH}  # Upload everything in the current directory
        EOF
      env:
        SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}  # Store your private key in GitHub Secrets
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
