name: Deploy Static Website via SFTP

on:
  push:
    branches:
      - main  # Trigger the deployment when pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub's Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Install sshpass
      run: sudo apt-get install -y sshpass  # Install sshpass for password authentication

    - name: Deploy files via SFTP using password authentication
      run: |
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -oPort=22 ${SFTP_USERNAME}@${SFTP_HOST} << EOF
        put -r ./ ${REMOTE_PATH}  # Upload all files in the current directory to the remote path
        EOF
      env:
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}  # cPanel username (e.g., 'makendsc')
        SFTP_HOST: ${{ secrets.SFTP_HOST }}  # cPanel SFTP host (e.g., 'ftp.makendsc.com')
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}  # Remote directory to deploy to (e.g., '/public_html/test-deploy')
