name: Deploy Static Website via SFTP

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on GitHub's Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up SSH for SFTP
      run: |
        mkdir -p ~/.ssh
        echo "$SFTP_PRIVATE_KEY" > ~/.ssh/id_rsa  # Use the private key from GitHub Secrets
        chmod 600 ~/.ssh/id_rsa  # Set the correct permissions
        echo "Host *" > ~/.ssh/config  # Disable strict host key checking
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

    - name: Deploy files via SFTP
      run: |
        sftp -oPort=${{ secrets.SFTP_PORT }} ${SFTP_USERNAME}@${SFTP_HOST} << EOF
        put -r ./ ${REMOTE_PATH}  # Upload all files in the current directory to the remote path
        EOF
      env:
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}  # Your SFTP username
        SFTP_HOST: ${{ secrets.SFTP_HOST }}  # Your SFTP host (e.g., ftp.makends.com)
        SFTP_PORT: ${{ secrets.SFTP_PORT }}  # Your SFTP port (typically 21)
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}  # Remote directory to deploy the files (e.g., /home/makendsc/test-deploy)
